name: "Auto Triage Slack Reporter"
description: "Format slack_message.json and send it to Slack."
inputs:
  slack_webhook_url:
    description: "Webhook URL for the Slack channel to be posted to."
    required: true
  slack_message_path:
    description: "Path to slack_message.json."
    required: false
    default: .auto_triage/output/slack_message.json
runs:
  using: "composite"
  steps:
    - name: Build Slack payload
      id: build
      shell: bash
      env:
        MESSAGE_PATH: ${{ inputs.slack_message_path }}
      run: |
        set -euo pipefail
        if [ -z "${MESSAGE_PATH:-}" ]; then
          echo "has_payload=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        if [ ! -f "$MESSAGE_PATH" ]; then
          echo "Slack message file '$MESSAGE_PATH' not found; skipping notification."
          echo "has_payload=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        RUN_LABEL="run #${GITHUB_RUN_NUMBER:-$GITHUB_RUN_ID}"

        TEXT=$(jq -r --arg run_url "$RUN_URL" --arg run_label "$RUN_LABEL" '
          def short_hash(h):
            if (h // "") == "" then "unknown" else (h[0:8]) end;

          def commit_link(c):
            if (c.url // c.commit_url // "") != "" then
              "<" + (c.url // c.commit_url) + "|" + short_hash(c.hash // c.commit) + ">"
            else short_hash(c.hash // c.commit)
            end;

          def person(p):
            if p == null then
              "Unknown"
            else
              (if (p.slack_id // "") != "" then "<@" + p.slack_id + ">" else (p.name // p.login // "Unknown") end)
            end;

          def join_people(arr):
            arr | map(person(.)) | join(", ");

          def section_line(lbl; txt):
            if (txt // "") != "" then "*\(lbl):* " + txt + "\n" else "" end;

          def section_people(lbl; arr):
            if (arr | type) == "array" and (arr | length) > 0 then
              "*\(lbl):* " + join_people(arr) + "\n"
            else "" end;

          def section_files(lbl; arr):
            if (arr | type) == "array" and (arr | length) > 0 then
              "*\(lbl):*\n```\n" + (arr | join("\n")) + "\n```\n"
            else "" end;

          def section_code(lbl; txt):
            if (txt // "") != "" then "*\(lbl):*\n```" + txt + "```\n" else "" end;

          def commit_entry(c):
            "- HASH: " + commit_link(c) + "\n"
            + "  AUTHOR: " + person(c.author) + "\n"
            + (if (c.approvers | type) == "array" and (c.approvers | length) > 0 then
                "  APPROVERS: " + join_people(c.approvers) + "\n"
              else "" end)
            + (if (c.relevant_developers | type) == "array" and (c.relevant_developers | length) > 0 then
                "  RELEVANT DEVELOPERS: " + join_people(c.relevant_developers) + "\n"
              else "" end)
            + (if (c.relevant_files | type) == "array" and (c.relevant_files | length) > 0 then
                "  RELEVANT FILES:\n```\n" + (c.relevant_files | join("\n")) + "\n```\n"
              else "" end);

          def commits_section(arr):
            if (arr | type) == "array" and (arr | length) > 0 then
              "*COMMITS:*\n" + (arr | map(commit_entry(.)) | join("\n")) + "\n"
            else "" end;

          (
            section_line("RUN"; "<\($run_url)|\($run_label)>")
            + section_line("CASE"; .case // "?")
            + section_line("SCENARIO"; .scenario)
            + section_code("FAILURE MESSAGE"; .failure_message)
            + (if (.slack_message // "") != "" then (.slack_message + "\n") else "" end)
            + commits_section(.commits)
            + section_people("RELEVANT DEVELOPERS"; .relevant_developers)
            + section_files("RELEVANT FILES"; .relevant_files)
            + section_line("NOTES"; .notes)
          ) | gsub("\n{3,}"; "\n\n")
        ' "$MESSAGE_PATH")

        if [ -z "$TEXT" ]; then
          echo "Parsed Slack message is empty; skipping notification."
          echo "has_payload=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        PAYLOAD=$(jq -cn --arg text "$TEXT" '{text: $text}')
        echo "payload=$PAYLOAD" >> "$GITHUB_OUTPUT"
        echo "has_payload=true" >> "$GITHUB_OUTPUT"

    - name: Report via Slack webhook
      if: steps.build.outputs.has_payload == 'true'
      shell: bash
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        PAYLOAD: ${{ steps.build.outputs.payload }}
      run: |
        set -euo pipefail
        if [ -z "${SLACK_WEBHOOK_URL:-}" ]; then
          echo "Slack webhook URL is not set."
          exit 1
        fi
        curl -s -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK_URL"

    - name: Skip Slack notification
      if: steps.build.outputs.has_payload != 'true'
      shell: bash
      run: echo "ℹ️ No Slack payload produced; notification skipped."

