---
name: auto-triage
description: Run auto_triage automation with GitHub Copilot CLI and GitHub API access.
inputs:
  workflow-name:
    description: Workflow file name to inspect.
    required: true
  job-name:
    description: Job/subjob name within the workflow.
    required: true
  model:
    description: Model identifier (kept for compatibility, currently unused).
    required: true
  filter-model:
    description: Model identifier for the filter stage (kept for compatibility, currently unused).
    required: true
  wilder-pat:
    description: Personal Access Token for GitHub/Copilot authentication.
    required: true
  slack-test-only:
    description: Skip analysis steps and only send a canned Slack message.
    required: false
    default: "false"
runs:
  using: composite
  steps:
    - name: Stage auto_triage scripts
      shell: bash
      run: |
        set -euo pipefail
        TARGET="${GITHUB_WORKSPACE}/.auto_triage"
        rm -rf "$TARGET"
        mkdir -p "$TARGET"
        # Copy triage tooling
        cp -R "${{ github.action_path }}/auto_triage/." "$TARGET/"
        chmod +x "$TARGET/"*.sh 2>/dev/null || true
        chmod +x "$TARGET/"*.py 2>/dev/null || true
        # Mirror the checked-out repo into the workspace for the LLM (excluding the workspace itself)
        rsync -a --delete \
          --exclude '.auto_triage/' \
          --exclude '.git/' \
          --exclude 'auto_triage/' \
          "$GITHUB_WORKSPACE"/ "$TARGET/workspace/"
        echo "$TARGET" >> "$GITHUB_PATH"
    - name: Find boundaries
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        ./find_boundaries.sh \
          "${{ inputs.workflow-name }}" \
          "${{ inputs.job-name }}"
    - name: Download Slack directory
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        ./download_slack_directory.py
    - name: Install ripgrep
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update && sudo apt-get install -y ripgrep
        rg --version || (echo "ripgrep installation failed" && exit 1)
    - name: Setup Node.js v22+
      if: inputs.slack-test-only != 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: Install GitHub Copilot CLI
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        npm install -g @github/copilot
        copilot --version || (echo "Copilot CLI installation failed" && exit 1)
    - name: Execute filter_triage.sh
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        # Verify authentication tokens are set
        if [ -z "${COPILOT_GITHUB_TOKEN:-}" ] && [ -z "${GH_TOKEN:-}" ] && [ -z "${GITHUB_TOKEN:-}" ]; then
          echo "Warning: No authentication tokens found in environment"
        fi
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        ./filter_triage.sh \
          "${{ inputs.workflow-name }}" \
          "${{ inputs.job-name }}" \
          "${{ inputs.filter-model }}" \
          ci
      env:
        # Use WILDER_PAT for Copilot CLI authentication
        COPILOT_GITHUB_TOKEN: ${{ inputs.wilder-pat }}
        # Use github.token for gh CLI (used by bash scripts for GitHub API calls)
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Produce filtered commit list
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        COMMIT_FILE="auto_triage/data/commit_info.json"
        FILTERED_FILE="auto_triage/data/filtered_commit_info.json"
        if [ ! -f "$COMMIT_FILE" ]; then
            echo "Filter stage did not produce $COMMIT_FILE" >&2
            exit 1
        fi
        if jq -e 'type=="array"' "$COMMIT_FILE" >/dev/null 2>&1; then
            jq '[.[] | select((.is_irrelevant // false) == false)]' "$COMMIT_FILE" > "$FILTERED_FILE"
        else
            cp "$COMMIT_FILE" "$FILTERED_FILE"
        fi
        if [ ! -f "auto_triage/data/error_message.txt" ]; then
            touch "auto_triage/data/error_message.txt"
        fi

    - name: Execute auto_triage.sh
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        ./auto_triage.sh \
          "${{ inputs.workflow-name }}" \
          "${{ inputs.job-name }}" \
          "${{ inputs.model }}" \
          ci
      env:
        REUSE_DATA: "true"
        # Use WILDER_PAT for Copilot CLI authentication
        COPILOT_GITHUB_TOKEN: ${{ inputs.wilder-pat }}
        # Use github.token for gh CLI (used by bash scripts for GitHub API calls)
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}
    - name: Seed Slack test payload
      if: inputs.slack-test-only == 'true'
      shell: bash
      run: |
        set -euo pipefail
        TARGET="${GITHUB_WORKSPACE}/.auto_triage/output"
        mkdir -p "$TARGET"
        cp "${{ github.action_path }}/auto_triage/sample_slack_message.json" "$TARGET/slack_message.json"

    - name: Send Slack notification
      if: always()
      uses: tenstorrent-metal/tt-auto-triage/.github/actions/slack-report-auto-triage@main
      with:
        slack_webhook_url: ${{ env.SLACK_WEBHOOK_URL }}
        slack_message_path: .auto_triage/output/slack_message.json
    - name: Publish triage report to summary
      if: always() && inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        REPORT="${GITHUB_WORKSPACE}/.auto_triage/output/explanation.md"
        if [ -f "$REPORT" ]; then
            {
              echo "## Auto Triage Report"
              cat "$REPORT"
            } >> "$GITHUB_STEP_SUMMARY"
        else
            echo "No explanation produced." >> "$GITHUB_STEP_SUMMARY"
        fi
    - name: Upload auto-triage data
      if: always() && inputs.slack-test-only != 'true'
      uses: actions/upload-artifact@v4
      with:
        name: auto-triage-data
        path: ${{ github.workspace }}/.auto_triage/data
        if-no-files-found: ignore
        include-hidden-files: true
    - name: Upload auto-triage output
      if: always() && inputs.slack-test-only != 'true'
      uses: actions/upload-artifact@v4
      with:
        name: auto-triage-output
        path: ${{ github.workspace }}/.auto_triage/output
        if-no-files-found: ignore
        include-hidden-files: true
