---
name: auto-triage
description: Run auto_triage automation with GitHub Copilot CLI and GitHub API access.
inputs:
  workflow-name:
    description: Workflow file name to inspect.
    required: true
  job-name:
    description: Job/subjob name within the workflow.
    required: true
  copilot-pat:
    description: Personal Access Token for GitHub/Copilot authentication.
    required: true
  slack-test-only:
    description: Skip analysis steps and only send a canned Slack message.
    required: false
    default: "false"
  slack_ts:
    description: "Slack message timestamp for threading replies"
    required: false
    default: ""
  allow-pings:
    description: "Whether to allow pinging users/groups in the Slack message."
    required: false
    default: "false"
  send-slack-message:
    description: "Whether to send a Slack message."
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Stage auto_triage scripts
      shell: bash
      run: |
        set -euo pipefail
        TARGET="${GITHUB_WORKSPACE}/.auto_triage"
        rm -rf "$TARGET"
        mkdir -p "$TARGET"
        # Copy triage tooling
        cp -R "${{ github.action_path }}/auto_triage/." "$TARGET/"
        chmod +x "$TARGET/"*.sh 2>/dev/null || true
        chmod +x "$TARGET/"*.py 2>/dev/null || true
        # Mirror the checked-out repo into the workspace for the LLM (excluding the workspace itself)
        rsync -a --delete \
          --exclude '.auto_triage/' \
          --exclude '.git/' \
          --exclude 'auto_triage/' \
          "$GITHUB_WORKSPACE"/ "$TARGET/workspace/"
        echo "$TARGET" >> "$GITHUB_PATH"
        # Initialize cancel.json with default state - this is the single source of truth for cancellation
        echo '{"should_cancel": false, "message": ""}' > "$TARGET/cancel.json"

    - name: Find boundaries
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        # Check cancel state
        if [ -f cancel.json ] && [ "$(jq -r '.should_cancel // false' cancel.json)" = "true" ]; then
          echo "Skipping: cancellation requested"
          exit 0
        fi
        ./find_boundaries.sh \
          "${{ inputs.workflow-name }}" \
          "${{ inputs.job-name }}"
      env:
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Download Slack directory
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        # Check cancel state
        if [ -f cancel.json ] && [ "$(jq -r '.should_cancel // false' cancel.json)" = "true" ]; then
          echo "Skipping: cancellation requested"
          exit 0
        fi
        ./download_slack_directory.py

    - name: Install ripgrep
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        # Check cancel state
        if [ -f cancel.json ] && [ "$(jq -r '.should_cancel // false' cancel.json)" = "true" ]; then
          echo "Skipping: cancellation requested"
          exit 0
        fi
        sudo apt-get update && sudo apt-get install -y ripgrep
        rg --version || (echo "ripgrep installation failed" && exit 1)

    - name: Setup Node.js v22+
      if: inputs.slack-test-only != 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install GitHub Copilot CLI
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        # Check cancel state
        if [ -f cancel.json ] && [ "$(jq -r '.should_cancel // false' cancel.json)" = "true" ]; then
          echo "Skipping: cancellation requested"
          exit 0
        fi
        npm install -g @github/copilot
        copilot --version || (echo "Copilot CLI installation failed" && exit 1)

    - name: Execute filter_triage.sh
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -uo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        # Check cancel state
        if [ -f cancel.json ] && [ "$(jq -r '.should_cancel // false' cancel.json)" = "true" ]; then
          echo "Skipping: cancellation requested"
          exit 0
        fi
        # Verify authentication tokens are set
        if [ -z "${COPILOT_GITHUB_TOKEN:-}" ] && [ -z "${GH_TOKEN:-}" ] && [ -z "${GITHUB_TOKEN:-}" ]; then
          echo "Warning: No authentication tokens found in environment"
        fi
        # Run filter_triage.sh with error handling - fail gracefully on any error
        if ! ./filter_triage.sh \
          "${{ inputs.workflow-name }}" \
          "${{ inputs.job-name }}" \
          ci; then
          echo "filter_triage.sh failed, setting cancellation flag"
          jq -n '{should_cancel: true, message: "Filter triage step failed unexpectedly. Check logs for details."}' > cancel.json
        fi
      env:
        # Use TESTING_COPILOT_PAT for Copilot CLI authentication
        COPILOT_GITHUB_TOKEN: ${{ inputs.copilot-pat }}
        # Use github.token for gh CLI (used by bash scripts for GitHub API calls)
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Write cancellation explanation
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        CANCEL_FILE="cancel.json"
        # Only write explanation if cancellation was requested
        if [ ! -f "$CANCEL_FILE" ] || [ "$(jq -r '.should_cancel // false' "$CANCEL_FILE")" != "true" ]; then
          echo "No cancellation requested, skipping"
          exit 0
        fi
        REPORT_DIR="${GITHUB_WORKSPACE}/.auto_triage/output"
        mkdir -p "$REPORT_DIR"
        RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
        RUN_LABEL="full_report_link #${GITHUB_RUN_NUMBER:-$GITHUB_RUN_ID}"
        CANCEL_MESSAGE=$(jq -r '.message // ""' "$CANCEL_FILE")
        {
          echo "*Auto-triage cancelled:*"
          echo "$CANCEL_MESSAGE"
          echo ""
          echo "*Workflow:* ${{ inputs.workflow-name }}"
          echo "*Job:* ${{ inputs.job-name }}"
          echo "*Run:* <$RUN_URL|$RUN_LABEL>"
        } > "$REPORT_DIR/explanation.md"

    - name: Verify filter stage outputs
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        # Check cancel state
        if [ -f cancel.json ] && [ "$(jq -r '.should_cancel // false' cancel.json)" = "true" ]; then
          echo "Skipping: cancellation requested"
          exit 0
        fi
        COMMIT_FILE="auto_triage/data/commit_info.json"
        if [ ! -f "$COMMIT_FILE" ]; then
            echo "Filter stage did not produce $COMMIT_FILE" >&2
            exit 1
        fi
        if [ ! -f "auto_triage/data/error_message.txt" ]; then
            touch "auto_triage/data/error_message.txt"
        fi

    - name: Execute auto_triage.sh
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        # Check cancel state
        if [ -f cancel.json ] && [ "$(jq -r '.should_cancel // false' cancel.json)" = "true" ]; then
          echo "Skipping: cancellation requested"
          exit 0
        fi
        ./auto_triage.sh \
          "${{ inputs.workflow-name }}" \
          "${{ inputs.job-name }}" \
          ci
      env:
        REUSE_DATA: "true"
        # Use TESTING_COPILOT_PAT for Copilot CLI authentication
        COPILOT_GITHUB_TOKEN: ${{ inputs.copilot-pat }}
        # Use github.token for gh CLI (used by bash scripts for GitHub API calls)
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Attempt auto fix PR (optional)
      if: inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        cd "${GITHUB_WORKSPACE}/.auto_triage"
        # Check cancel state
        if [ -f cancel.json ] && [ "$(jq -r '.should_cancel // false' cancel.json)" = "true" ]; then
          echo "Skipping: cancellation requested"
          exit 0
        fi
        ./run_auto_fix.sh \
          "${{ inputs.workflow-name }}" \
          "${{ inputs.job-name }}"
      env:
        COPILOT_GITHUB_TOKEN: ${{ inputs.copilot-pat }}
        GH_TOKEN: ${{ github.token }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: Seed Slack test payload
      if: inputs.slack-test-only == 'true'
      shell: bash
      run: |
        set -euo pipefail
        TARGET="${GITHUB_WORKSPACE}/.auto_triage/output"
        mkdir -p "$TARGET"
        cp "${{ github.action_path }}/auto_triage/sample_slack_message.json" "$TARGET/slack_message.json"

    - name: Debug Slack send configuration
      if: always()
      shell: bash
      run: |
        set -euo pipefail
        echo "Auto-triage Slack send flag (inputs.send-slack-message) = '${{ inputs.send-slack-message }}'"
        echo "Auto-triage Slack thread timestamp (inputs.slack_ts) = '${{ inputs.slack_ts }}'"
        if [ "${{ inputs.send-slack-message }}" = "true" ]; then
          echo "Auto-triage: Slack notification step is ENABLED and will run (barring job-level skips)."
        else
          echo "Auto-triage: Slack notification step is DISABLED and will NOT run."
        fi

    - name: Send Slack notification
      if: always() && inputs.send-slack-message == 'true'
      uses: tenstorrent-metal/tt-auto-triage/.github/actions/slack-report-auto-triage@main
      with:
        # slack_webhook_url is no longer used, using env.SLACK_BOT_TOKEN and env.SLACK_CHANNEL_ID instead inside the action
        channel_id: ${{ env.SLACK_CHANNEL_ID }}
        slack_message_path: .auto_triage/output/slack_message.json
        job_name: ${{ inputs.job-name }}
        workflow_name: ${{ inputs.workflow-name }}
        auto_fix_meta_path: .auto_triage/data/auto_fix_metadata.json
        slack_ts: ${{ inputs.slack_ts }}
        allow_pings: ${{ inputs.allow-pings }}

    - name: Publish triage report to summary
      if: always() && inputs.slack-test-only != 'true'
      shell: bash
      run: |
        set -euo pipefail
        REPORT="${GITHUB_WORKSPACE}/.auto_triage/output/explanation.md"
        if [ -f "$REPORT" ]; then
            {
              echo "## Auto Triage Report"
              cat "$REPORT"
            } >> "$GITHUB_STEP_SUMMARY"
        else
            echo "No explanation produced." >> "$GITHUB_STEP_SUMMARY"
        fi

    - name: Upload auto-triage data
      if: always() && inputs.slack-test-only != 'true'
      uses: actions/upload-artifact@v4
      with:
        name: auto-triage-data
        path: ${{ github.workspace }}/.auto_triage/data
        if-no-files-found: ignore
        include-hidden-files: true

    - name: Upload auto-triage output
      if: always() && inputs.slack-test-only != 'true'
      uses: actions/upload-artifact@v4
      with:
        name: auto-triage-output
        path: ${{ github.workspace }}/.auto_triage/output
        if-no-files-found: ignore
        include-hidden-files: true
